@echo off

echo Start build..
echo Compile boot.s...
.\windows\bin\i686-elf-as.exe  reduceOS/boot.s -o build/boot.o
echo Finish boot.s...
echo Compile kernel.c...
.\windows\bin\i686-elf-gcc.exe -c reduceOS/kernel.c -o build/kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
echo Finish kernel.c...
echo Link reduce.bin...
.\windows\bin\i686-elf-gcc.exe -T linker.ld -o build/reduce.bin -ffreestanding -O2 -nostdlib build/boot.o build/kernel.o -lgcc
echo Finish reduce.bin...

echo Done!