# Base makefile

# Target disabled
all:
	@echo "=== TARGET DISABLED ==="
	@echo "Please use make install"


# Cosmetic
PRINT_HEADER:
	@echo
	@echo
	@echo "[ Creating base, please wait... ]"
	@echo
	@echo


install-headers:
	-cp -rp initrd/* $(INITRD)/
	-cp -rp sysroot/* $(SYSROOT)/